### PR TITLE
Restructure features

### LINKED ISSUE #10: Review feature categorizations
We should review the titles and categorization of the terms, as I believe this was added to the wiki only to help break up the long list of values.

I was skimming the values and noticed some, at least, may be misplaced -- highContrastAudio isn't necessarily in a transformed state or able to be transformed, for example, and neither arguably is large text print (it may be the only way it's published and large print isn't necessarily intended for further transformation).

### PR DESCRIPTION
**Pull request by mattgarrish**
We'll probably want to do some iterations on this, but here's my first attempt at restructuring.

The groupings in the PR are as follows:

```
- Structure and Navigation Terms
   - annotations
   - bookmarks
   - index
   - printPageNumbers
   - readingOrder
   - structuralNavigation
   - taggedPDF

- Adaptation Terms
   - alternativeText
   - audioDescription
   - captions
   - describedMath
   - longDescription
   - rubyAnnotations
   - signLanguage
   - transcript

- Rendering Control Terms
   - displayTransformability
   - synchronizedAudioText
   - timingControl
   - unlocked

- Specialized Markup Terms
   - ChemML
   - latex
   - MathML
   - ttsMarkup

- Clarity Terms
   - highContrastAudio
   - highContrastDisplay
   - largePrint

- Tactile Terms
   - braille
   - tactileGraphic
   - tactileObject

- none
```

It maybe makes the groups a bit too atomic, but I found the previously version led to trying to accommodate too many terms under headings they didn't fit all that well.

Fixes #10

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/a11y-discov-vocab/pull/34.html" title="Last updated on Jan 26, 2022, 4:51 PM UTC (7b118b1)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/a11y-discov-vocab/34/cb10f3e...7b118b1.html" title="Last updated on Jan 26, 2022, 4:51 PM UTC (7b118b1)">Diff</a>

### CODE REVIEW

**Review by clapierre — APPROVED** [review]

**Comment by madeleinerothberg** [comment]
I think these groupings are good. Thanks for putting this list together. A few comments:

- Was there a reason you put signLanguage under Playback? I think of it as being similar to captions and audioDescription. 
- Is ttsMarkup Special Markup?
- Is displayTransformability Playback, for a loose definition of Play? 
- Is unlocked more structure/navigation? I think the point of knowing it is unlocked is that you can navigate it differently or in different software if you wish.

**Comment by mattgarrish** [comment]
> Was there a reason you put signLanguage under Playback?

The description for it says:

> Synchronized sign language interpretation is available for audio and video content.

Like synchronized audio/text, I'm assuming this means whether to turn it on is controlled by the user. It could also fit under the adaptations, as I don't think there's one right answer for this, but then audio sync could arguably also go there, too.

> Is ttsMarkup Special Markup?

Ya, that's one I moved back and forth a couple of times. Since we weren't calling out a specific markup for TTS, I tossed it into the adaptations bucket. I'm fine either way, though.

> Is displayTransformability Playback, for a loose definition of Play

It's a hard one to pin down. I actually thought about it going in the clarity section along with large print, but being transformable doesn't mean you can transform the content, so it may not improve anything. It doesn't really fit in playback, either, as there's no timing aspect to it. But maybe there's a better name than "playback" that could make it work?

> Is unlocked more structure/navigation?

It's not really about the structure or navigation, but rights restrictions on top of the publication. It was originally in the same bucket as synchronized audio and timing control, but those didn't group well as "content control". It's more of a lone access issue. Again, maybe there's some other grouping than "playback" we could use to group these, though.

**Comment by mattgarrish** [comment]
> Synchronized sign language interpretation is available for audio and video content.

I wonder if "synchronized" is a bit misleading here. It's certainly not widely done for audio, and with video it's generally part of the video, not a separate synchronization.

Maybe we could just drop the word and move this into adaptations?

**Comment by madeleinerothberg** [comment]
> > Synchronized sign language interpretation is available for audio and video content.
> 
> I wonder if "synchronized" is a bit misleading here. It's certainly not widely done for audio, and with video it's generally part of the video, not a separate synchronization.
> 
> Maybe we could just drop the word and move this into adaptations?

That's a great suggestion.

**Comment by madeleinerothberg** [comment]
displayTransformability:
What did you mean by 
> but being transformable doesn't mean you can transform the content

An alternative name for Playback would be good. I'm trying to think how to reference "while reading" or "in the reading system" without it meaning either all features, since they are all for reading when it comes down to it, or only features of the reading system. I think this list is "features of the book that the reading system can use to do cool things during reading." But maybe that's still too broad.

**Comment by mattgarrish** [comment]
I've made a few changes that are now reflected in the outline in the first comment:

- ttsMarkup is now in the specialized markup section
- signLanguage is now in adaptations and no longer has the word "synchronized"
- I've renamed "Playback" to "Rendering Control" for now, but we can continue to improve it
- unlocked and displayTransformability are now under the new Rendering Control heading

**Review by madeleinerothberg — APPROVED** [review]

**Pull request merged**
