### PR TITLE
Add pageNavigation and pageBreakMarkers feature values

### LINKED ISSUE #6: Add page navigation to accessibility features
While reviewing the `accessibilityFeature` values, I noticed that we have "printPageNumbers" but don't have a value that specifically indicates that page navigation is available.

There's maybe a fine distinction here, but indicating a publication has print page numbers doesn't necessarily mean that it has a page list (although you'd sort of hope that would be the case). Similarly, as we know, if a publication has a page list it doesn't mean that page breaks have to come from a print source, which makes what to specify for that case confusing.

My suggestion is that we introduce an explicit "pageNavigation" value to use when a publication has a page list. It can be paired with "printPageNumbers" to indicate that the publication's static pagination matches a print source.

### PR DESCRIPTION
**Pull request by mattgarrish**
This pull request fixes #6 by adding the two values discussed in that issue.

In adding pageBreakMarkers, I've made printPageNumbers a synonym that we no longer recommend using. This will avoid invalidating existing content by deprecating the value.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/a11y-discov-vocab/pull/51.html" title="Last updated on Mar 6, 2023, 7:32 PM UTC (bd7b6d6)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/a11y-discov-vocab/51/4b79b17...bd7b6d6.html" title="Last updated on Mar 6, 2023, 7:32 PM UTC (bd7b6d6)">Diff</a>

### CODE REVIEW

**Comment by clapierre** [comment]
So basically this means that in order to determine if there is a Print equivalent for the page numbers you would first see if accessibilityFeature has pagebreakMarker, then look up the dc:source and its refines to ensure its the source-of the pagination within this EPUB.  I guess so, I guess  I am still confused, as ultimately I want to know if this is 

Knowing that there is pagebreakMarkers alone tells me I can go to a specific page which is good, but in the use-case where I am a student and need to get to the same page as my peers then I need to cross reference the ISBN # of the dc:source of the pagination with the ISBN of the print book they have and hope that there aren't multiple versions because the dc:source was pointing to the hard-cover ISBN, but they are using the soft-cover version which is a different ISBN and maybe those pages match but maybe not.  

Would love to hear from publishers on how page numbering maps across various print books.

**Comment by mattgarrish** [comment]
There's probably also a case for a more specific property than dc:source, since it necessitates a hack to try and make it machine readable.

We might want to consider incubating an `a11y:pageSource` property, for example, to get rid of that awful `source-of` property refinement. That's likely doomed to the dustbin in the long run no matter what.

It would at least make a little more sense to have `<meta property="a11y:pageSource">none<meta>` than abuse `dc:source`.

**Comment by madeleinerothberg** [comment]
Not my expertise -- proceed without my review when everyone else agrees.

**Comment by clapierre** [comment]
I do like the idea of adding a11y:pageSource which would recommended to be the ISBN of the print equivalent if that is where the pagebreaks are mapped to.  

I would also like to have a clear recommendation for what it would say when this is a digital Only pagebreaks added by the publisher when there is no print equivalent as in digital first publications.  

If we document that "none" (or something similar) should be used for this case I am fine with this as I always wanted some way to know that the pagebreaks were put in to this digital version only (hence the original idea of self referencing which wasn't ideal either).

**Review by clapierre — APPROVED** [review]
This is great.
Just wondering if  this should be` ...>doc-pagelist</a> not just ...>pagelist</a>.`

`<a href="https://www.w3.org/TR/dpub-aria/#doc-pagelist"
 								>pagelist</a> role [[DPUB-ARIA-1.0]]`

**Pull request merged**
