### PR TITLE
removed these two unused sections

### PR DESCRIPTION
**Pull request by clapierre**
We don't reference these accessibilityAPI nor accessibilityControl in our EPUB Accessibility specification no need to include them in the crosswalk.

### CODE REVIEW

**Comment by mattgarrish** [comment]
Should it be taken out or would it help to change the current dashes to something like "N/A" so people understand they're not applicable?

**Comment by clapierre** [comment]
It was my impression that we no longer encourage accessibilityAPI nor accessibilityControls in an EPUB this is a feature of the reading system which is why I think just removing them entirely makes the most sense as it really doesn't apply to EPUBs.

**Comment by mattgarrish** [comment]
Ya, but if you remove them then you invite people to question if we've forgotten to map them. Another alternative would be to leave the group heading in the table and write out below it in a single cell what you just said so they understand these no longer apply.

**Comment by clapierre** [comment]
@mattgarrish Updated the pull request to reflect your suggestion. Feel free to suggest any updated text changes.

**Comment by mattgarrish** [comment]
lgtm!

**Review by gregoriopellegrino — APPROVED** [review]

**Pull request merged**
