### PR TITLE
Added codelist 196:93 for certifierCredential ONIX equivalent

### PR DESCRIPTION
**Pull request by clapierre**
Adding support for certifierCredential in light of Gramham's email 

From Graham Bell:
For the use case you describe (a generic link – same link for all certified publishers), 93 is probably more appropriate.

If there a ‘deeper' URL that can point to an individual publisher’s credentials? Or one that provides any detail beyond ‘I am certified’? Maybe even a list of certified publishers? That’s what you’d use 94 for.

I will also add this example (using 93 and the generic link, unless there is another option) to our Implementation and Best Practice Guide.

### CODE REVIEW

**Comment by clapierre** [comment]
As far as #61, I agree except it also mentions this could potentially also fix certifiedBy, which I don't think it does. as Benetech has two GCA evaluations ours plus eBoundCanada. Both of which point to our GCA Credential URL, but ours is "CertifiedBy: Benetech" the other is "CertifiedBy: Benetech via eBoundCanada". This nuance is still to be addressed.

**Comment by madeleinerothberg** [comment]
I'm not well-informed on this one. If Charles and Matt think it works, then it's fine with me.

**Comment by mattgarrish** [comment]
I'm still concerned that we're not using the official name for Code 93. All the other mappings use the exact headings listed on this page: https://ns.editeur.org/onix/en/196

What if I go through the table and update all those links to go their definition pages rather than have them all going to the generic link?

For example, this definition could be:

> [List 196: Code 93:  Compliance certification by](https://ns.editeur.org/onix/en/196/93)

Would that work for you @clapierre ?

I only see additional explanations added for the complicated values, like the access modes, that involve multiple code values (although even those list the official headings for each).

**Comment by clapierre** [comment]
Sure I think thats a great idea Matt.

**Comment by mattgarrish** [comment]
I've gone through and updated all the linking and added titles for any codes that were missing. I also linked all the conformance and schema.org values to their definitions so you can get more info on whichever property you're unfamiliar with.

**Review by mattgarrish — APPROVED** [review]

**Pull request merged**
